checkmarx-ltd/CLI

src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
force scan will be done only if both flags doesn't appear -forcescan and -disableforcescan.
=> Added the DisableForceScan flag

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
removed the disableforcescan flag, and fixed the forcescan logic
=> fix the forceScan flag logic and delete the disable force scan

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java
change the description of the force scan to original description, and update the version to 2020.1.4
=> change force scan description

pom.xml
added properties to pom.xml that enable connection to SonarCloud and execution of scan
=> add sonarcloud scan ability to the project

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter.yml, .github/workflows/release-drafter.yml, CONTRIBUTING.md, Dockerfile, README.md, docker-compose.yml
(readme, contributing, templates, etc) + release drafter
=> Added open-source readiness files

pom.xml
=> Update pom.xml to change cli plugin name to CxConsolePlugin

pom.xml
=> Update pom.xml to point to last common

pom.xml
=> Point to last common

pom.xml, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> add support with async sca scan and update plugin version and fix text of zipped sources to zipped data 

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java
=> raise version to 2020.3.7 and remove unused function

pom.xml
=> Update pom.xml with new common version (including new FSA 20.0.8)

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/utils/ErrorParsingHelper.java
=> raise version to 2020.3.10 and make it work with common 2020.3.83

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/constants/UsageExamples.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java, src/main/java/com/cx/plugin/cli/utils/ErrorParsingHelper.java, src/main/java/com/cx/plugin/cli/utils/PropertiesManager.java, src/main/java/com/cx/plugin/cli/utils/ScanSourceConfigurator.java
=> fixed sonar issues and upgrade version to 2020.4.1

pom.xml
=> upgrade version to 2020.4.2 and common version to 2020.4.94

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java
=> revert log4j.xml exclude from jar and raise version to 2020.4.3

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java
=> Made different scanners loosely coupled and run independently

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> fix osa and sca reporting mechanism and raise version to 2020.4.5

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
> This PR adds the support for using NTLM proxy.
> Manual testing done using WinGate.
=> Added support for ntlm proxy support.

pom.xml, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> Fixed vulnerabilities

pom.xml
=> Updated common-client version that includes SAST 8.9 scan fix

pom.xml
=> remove sonar token from pom

pom.xml
=> Vulnerabilityfix

src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
1. SCA project name cannot contain given special characters
2. Assign team while creating new sca project
3. Support both "/" or "\" based project fullpath  for the value of -projectName command line argument.
Feature 1561 and 1562
1. Validates that SCA project name does not contain special characters that are not allowed.
2. Extract team from project full path received from command line
3. Support either / or \ based full project path on the command line
NA - Merge on integration branch.
=> Assign team while creating project in sca

src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
> To merge the changes done for environment variables and config files from package managers and sca flag feature to include source code in SCA scan .
> After you run CLI command with -includesource option, in the logs should see the "Source Directory" and "Uploading the zipped data" 
>For exploitable path :> Once the SCA scan is over with passing SAST project details (-cxuser , -cxServer , -cxpassword, -cxProjectid ), When you click on vulnerabilities tab for the SCA project (for existing project you need to enable the settings in project settings -> enable exploitable path toggling), you can see the graph for attack vector)
=> Environment variables exploitable path

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Fixed the multiple package manager config file issue.
Now it will zip all the config files passed from CLI as argument
Tested all combinations with maven and npm package manager config files. Tested with include source and without include source switch
=> Cli sca features

src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=>  SCA scan timeout

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> Sca timeout feature

src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Scan level custom field implementation.
=> Completed the Scan level custom field implementation for CLI

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
SCA Resolver feature, SCA Time out , vulnerability fixes in 1.1.7 and 1.1.8
=> Cli release integration branch

pom.xml
Uptake of log4j library version 2.17.1
=> Uptake of log4j library version 2.17.1

pom.xml
1. Fixing Spring shell and netty codec vulnerability
=> Spring vul fix

src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Have stored the location_url in the value1 string. Then split that string with a '@' character. Converted characters before '@' to '*' by iterating it into for loop and stored that string into value variable. Then appended '@' and next part of '@' into value.
> …
=> Fix for CLI Plugin Shows Git Token in Plain Text

src/main/java/com/cx/plugin/cli/configascode/SastConfig.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/constants/UsageExamples.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Code changes for ability to run full scan after x incremental scans.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality …
=> Code changes for ability to run full scan after x incremental scans.

src/main/java/com/cx/plugin/cli/configascode/SastConfig.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/constants/UsageExamples.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Code changes for plug-12 project branch support.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests …
=> Code changes for plug-12 project branch support.

pom.xml
Fix for plug 606 vulnerabilities reported.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should …
=> Fix for plug 606 vulnerabilities.

pom.xml, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> CLI parameters to create a SCA report in XML\PDF\CSV format

.gitignore, config/cx_console.properties, pom.xml, src/main/java/com/cx/plugin/cli/configascode/SastConfig.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/constants/UsageExamples.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java, src/main/java/com/cx/plugin/cli/utils/PropertiesManager.java, src/main/java/com/cx/plugin/cli/utils/ScanSourceConfigurator.java
=> Nov22 integration branch

pom.xml
This PR includes library upgrade of guava, json, google-collections library to fix high and medium  possible vulnerability
=> Security fix plug 974

pom.xml, src/main/java/com/cx/plugin/cli/configascode/SastConfig.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
AvoidDuplicateProjectScans parameter : JIRA_PLUG_1159
Sample command:
runCxConsole.cmd Scan -v -ProjectName "CxServer/dupProjTest2" -TrustedCertificates -CxServer https://sast94.cxquality.com/ -cxuser  username -cxpassword <p****> -LocationType folder -LocationPath "C:\CLIPlugin\GitRepo\JavaVulnerableLabE" …
=> October integration

src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
> To print plugin version in configurations log
> Verfied the CLI Plugin version is getting displayed in logs in where configuration is getting printed.
=> print plugin version in configurations log

pom.xml
=> 2024Q3 SCA Vulnerability fix

src/main/java/com/cx/plugin/cli/configascode/SastConfig.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
=> Plug 1931 Changes

pom.xml, src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java, src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java, src/main/java/com/cx/plugin/cli/constants/Command.java, src/main/java/com/cx/plugin/cli/constants/Parameters.java, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
- Added a new parameter loglevel
- Added warning regarding deprecating of parameter AvoidDuplicateProjectScans
- Added plugin name and version in headers of api calls
- Added support for OpenJdk21
- Added changes to use Project Default preset if preset is not specified in the parameters
- Vulnerability fixes 
> A round of QA testing is done to do progression and regression testing.
> Tested SAST, SCA and OSA scan.
=> 2024 q4 release2 integration branch

config/cx_console.properties, pom.xml, src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java, src/main/java/com/cx/plugin/cli/utils/PropertiesManager.java
=> 2025 q2 integration branch
